name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archive with v and s directories
        run: |
          tar -czvf web-font-${{ github.ref_name }}.tar.gz v s

      - name: Create archive with install-font directory
        run: |
          tar -czvf install-font-${{ github.ref_name }}.tar.gz install-font/${{ github.ref_name }}

      - name: Upload archives to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            web-font-${{ github.ref_name }}.tar.gz
            install-font-${{ github.ref_name }}.tar.gz
