name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archive with v and s directories
        run: |
          tar -czvf openfonts-${{ github.ref_name }}.tar.gz v s

      - name: Upload archive to Release
        uses: softprops/action-gh-release@v2
        with:
          files: openfonts-${{ github.ref_name }}.tar.gz
